### ISSUE TITLE
variable population size

### ISSUE THREAD

**Issue by lorenzocapp** [4ment/phylostan#4]
Hello, 

Congrats on the excellent work. More than issues, mine are questions on how to use the software:

- I have not fully understood how to try phylostan for variable population size. I have tried in the two stages  (build and run) to add "-c skyride" or "-c skygrid," but I always get somehow estimates for the constant population.  At least, that's what the output on the terminal suggests. The output file also includes the same number of parameters, and there is a single theta (I would expect for variable population size this number to change)
- Could you also please share some post-processing files/instructions? I am unsure how to manage the output file, so I have not been able to generate any of the posterior plots myself.

Thanks a lot! 

Lorenzo

**Comment by 4ment** [comment]
Hi Lorenzo,

I have tried skyride and skygrid and I don't get the constant pop size estimate.
Have you used phylostan with the constant size model before using skyride/skygrid? Maybe the stan model was not recompiled. If it is the case you can either delete the pkl file or use `--compile` when you use the build or run commands.

I usually edit the output file with the samples so I can open it with [tracer](https://beast.community/tracer). The file containing the trees can be opened with [figtree](https://github.com/rambaut/figtree) and you can summarise the trees using [treeannotator](https://beast.community/treeannotator).

**Comment by lorenzocapp** [comment]
Thanks a lot, Mathieu, for the prompt reply.

I was indeed running the constant size model first and I was not recompiling. 

On the second topic, is the conversion of the output to a tracer obvious? Apologies if this is trivial, I have tried to look into .log files that one gets from BEAST and they seem more structured. 

Thanks a lot!
